import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to My page!</h1>
        <div className={styles.grid}>
          <a href="/comp/test" className={styles.cardS}>
            <h2>Plese click here to check my super page</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
