version: '3'

services:
  uploader-front:
    build: ./uploaderd-front
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./uploaderd-front:/app
    depends_on:
      - uploader-back

  uploader-back:
    build: ./uploader-back
    restart: always
    ports:
      - '4444:4444'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
