version: '3'

services:
  frontend-sql:
    build: ./frontend-sql
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - /app/.next
      - ./frontend-sql:/app
    depends_on:
      - backend-sql
  backend-sql:
    build: ./backend-sql
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./backend-sql:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: 'password'
      MYSQL_DB: 'Articles'
      CHOKIDAR_USEPOLLING: 'true'

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Articles
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  mysql_data:
